// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package errors

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/dizars1776/library-lite/internal/templates/layout"

func NotFound() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"font-sans text-[#333] mx-auto max-w-6xl max-md:max-w-md\"><div class=\"grid md:grid-cols-2 h-full justify-center md:items-center md:gap-8 gap-6\"><div class=\"max-md:order-1 max-md:text-center\"><p class=\"text-sm font-bold text-primary mb-2\"><span class=\"rotate-90 inline-block mr-2\">|</span>Adventure not found!</p><h1 class=\"md:text-6xl text-3xl font-extrabold mb-4 md:!leading-[55px]\">404</h1><p class=\"mt-4 text-base text-gray-500 leading-relaxed\">Perhaps you'd like to embark on a different reading journey?</p><div class=\"mt-10\"><button hx-get=\"/\" hx-target=\"body\" hx-push-url=\"true\" type=\"button\" class=\"bg-primary hover:bg-accent text-white hover:text-white font-bold text-sm rounded-full px-6 py-2.5 transition-colors\">Return to Home</button></div></div><div class=\"lg:h-[650px] md:h-[550px] flex items-center relative max-md:before:hidden before:absolute before:bg-cream before:h-full before:w-3/4 before:right-0 before:z-0\"><img src=\"/img/errors/book-falling.jpg\" class=\"rounded-md lg:w-3/4 md:w-11/12 z-50 h-[80%] relative object-cover\" alt=\"Book falling\"></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.ErrorIndex("lIlI - Page Not Found").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
